spring:
  application:
    name: customer-server
  config:
    import: "optional:configserver:http://localhost:8088"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3306/customer-management"
    username: springstudent
    password: springstudent


server:
  port: 8100


management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level:%5p [${spring.application.name:},%X{traceId:-},%X{spanId: